/** Permission strings — keep in sync with backend PERMISSION_NAMES. */
export const PERMISSIONS = {
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_ERASE: 'users.erase',
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_EDIT: 'roles.edit',
  ROLES_DELETE: 'roles.delete',
  PERMISSIONS_VIEW: 'permissions.view',
  PERMISSIONS_CREATE: 'permissions.create',
  PERMISSIONS_EDIT: 'permissions.edit',
  PERMISSIONS_DELETE: 'permissions.delete',
  ACTIVITY_VIEW: 'activity.view',
  CLIENTS_VIEW: 'clients.view',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_EDIT: 'clients.edit',
  CLIENTS_DELETE: 'clients.delete',
  UPLOADS_VIEW: 'uploads.view',
  UPLOADS_CREATE: 'uploads.create',
  UPLOADS_PURGE: 'uploads.purge',
  EMPLOYEES_VIEW: 'employees.view',
  FILINGS_VIEW: 'filings.view',
  FILINGS_CREATE: 'filings.create',
  FILINGS_EDIT: 'filings.edit',
  FILINGS_GENERATE: 'filings.generate',
  FILINGS_SEND: 'filings.send',
  TEMPLATES_VIEW: 'templates.view',
  TEMPLATES_CREATE: 'templates.create',
  TEMPLATES_EDIT: 'templates.edit',
  TEMPLATES_DELETE: 'templates.delete',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
